export const REQUEST_CHAIN_SIZE = 'REQUEST_CHAIN_SIZE';
export const RECEIVE_CHAIN_SIZE = 'RECEIVE_CHAIN_SIZE';
export const FAILED_CHAIN_SIZE = 'FAILED_CHAIN_SIZE';

export const REQUEST_AV_REWARD = 'REQUEST_AV_REWARD';
export const RECEIVE_AV_REWARD = 'RECEIVE_AV_REWARD';
export const FAILED_AV_REWARD = 'FAILED_AV_REWARD';

export const REQUEST_Y_RETURN = 'REQUEST_Y_RETURN';
export const RECEIVE_Y_RETURN = 'RECEIVE_Y_RETURN';
export const FAILED_Y_RETURN = 'FAILED_Y_RETURN';